name: "Build: Android"
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      semver:
        required: true
        type: string
  push:
    branches: [ "main" ]
    paths: [ "frontend" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "frontend" ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps: 
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Install yarn Dependencies'
        run: |
          yarn install

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: 'Build Android Release'
        run: |
          cd android
          ./gradlew assembleRelease

      - name: 'Get Commit Hash'
        id: commit
        uses: pr-mpt/actions-commit-hash@v1

      - name: 'Upload .apk Release Artifact (for Release)'
        uses: actions/upload-artifact@v3
        if: inputs.semver != ''  # If this workflow is called from release.yml
        with:
          name: nostros-${{ inputs.semver }}.apk
          path: android/app/build/outputs/apk/release/app-release.apk

      - name: 'Upload .apk Artifact (for Pre-release)'
        uses: actions/upload-artifact@v3
        if: inputs.semver == ''  # only if this workflow is not called from a push to tag (a Release)
        with:
          name: nostros-${{ steps.commit.outputs.short }}.apk
          path: android/app/build/outputs/apk/release/app-release.apk

      - name: 'Create Pre-release'
        id: create_release
        if: inputs.semver == ''  # only if this workflow is not called from a push to tag (a Release)
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: android-${{ steps.commit.outputs.short }}
          release_name: nostros-android-${{ steps.commit.outputs.short }}
          changelog: CHANGELOG.md
          draft: false
          prerelease: true

      - name: 'Upload Pre-release APK Release Asset'
        id: upload-release-apk-asset 
        if: inputs.semver == '' # only if this workflow is not called from a push to tag (a Release)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./android/app/build/outputs/apk/release/app-release.apk
          asset_name: nostros-${{ steps.commit.outputs.short }}.apk
          asset_content_type: application/apk
