name: "Build: Frontend All Bundles"

on:
  push:
    branches: [ "main" ]
    paths: [ "frontend" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "frontend" ]

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3
    - name: 'Setup node'
      uses: actions/setup-node@v3
      with:
        node-version: 16.17.0
        cache: yarn
        cache-dependency-path: frontend/package-lock.json
    - name: 'Install NPM Dependencies'
      run: |
        cd frontend
        yarn install
    - name:  'Format'
      run: |
        cd frontend
        yarn format