
name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      semver: ${{ steps.validate.outputs.semver }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Expose Version'
        id: validate
        shell: bash
        run: |
          semver=$(git describe --tags --abbrev=0)
  android-build:
    uses: KoalaSat/nostros/.github/workflows/android-build.yml@main
    needs: [check-version]
    with:
      semver: ${{ needs.check-version.outputs.semver }}
  release:
    needs: [android-build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Generate Release Changelog"
        id: changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        id: create-release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.changelog.outputs.changelog }}

      # Upload APK artifact asset
      - name: 'Download APK Artifact'
        uses: actions/download-artifact@v3
        with:
          name: nostros-${{ needs.check-version.outputs.semver }}.apk
          path: .
      - name: 'Upload APK Asset'
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: app-release.apk
          asset_name: nostros-${{ needs.check-version.outputs.semver }}.apk
          asset_content_type: application/apk